openapi: 3.0.0
info:
  version: '1.0'
  title: Murmurations Index API
  description: Draft version of the Index API for the Murmurations Protocol
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MurmurationsNetwork/IndexAPI/1.0
tags:
  - name: Node Endpoints
  - name: Aggregator Endpoints
paths:
  /nodes:
    post:
      tags:
        - Node Endpoints
      summary: Add a node to the index
      description: |
        A node adds its profile to the index by posting the location of the profile (`profileUrl`) and a list of one or more schemas (`linkedSchemas`) against which the profile must be validated.
        
        Each `linkedSchemas` item is a hash of a schema which can be found in the library using the following URL format: `{baseUrl}/schemas/{schemaHash}.json`. For example:
        
        `https://library.site/schemas/455521A0...18533249.json`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostNodeRequest'
            example:
              value:
                profileUrl: "https://node.site/optional-subdirectory/node-profile.json"
                linkedSchemas:
                  - "demo_schema-v1"
                  - "some_other_schema-v1"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/PostNodeResponse'
              example:
                data:
                  nodeId: "59776ca5caf24db9669d847bba3a13bd7052da0a8cccd548a335d8c88d186ce3"
                  lastChecked: 1601979232403
        # TODO: Add non-generic error responses (e.g., `Failed validation with schema: {schemaName}`, `Profile not found at profileUrl: {profileUrl}`, etc.)
        400:
          $ref: '#/components/responses/BadRequest'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500: 
          $ref: '#/components/responses/ServerError'
    get:
      tags:
        - Aggregator Endpoints
      summary: Search for nodes
      description: |
        Aggregators must authenticate themselves with a JWT to access this endpoint.
        
        Aggregators can search for nodes based on any of the following parameters:
        
        - A specific schema (`schemaName`)
        - When the node was last checked by the index (`lastChecked`)
        - A radius range (in kilometers) from a specific location (e.g., _"25km from my current location"_)
      parameters:
        - $ref: '#/components/parameters/schemaName'
        - $ref: '#/components/parameters/lastChecked'
        - $ref: '#/components/parameters/latitude'
        - $ref: '#/components/parameters/longitude'
        - $ref: '#/components/parameters/radius'
        - $ref: '#/components/parameters/locality'
        - $ref: '#/components/parameters/region'
        - $ref: '#/components/parameters/country'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GetNodesResponse'
              example:
                data:
                  - profileUrl: "https://node.site/optional-subdirectory/node-profile.json"
                    lastChecked: 1601979232403
                    geolocation:
                      latitude: 51.509865
                      longitude: -0.118092
                    mapAddress:
                      locality: London
                      region: Greater London
                      country: United Kingdom
        # TODO: Add non-generic error responses (e.g., `schemaName does not exist: {schemaName}`, `Invalid latitude (must be number): {latitude}`, etc.)
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500: 
          $ref: '#/components/responses/ServerError'
      security:
        - jwt: []
  /nodes/{nodeId}:
    get:
      tags:
        - Node Endpoints
      summary: Get a node's status from the index
      description: |
        TBC
      parameters:
        - $ref: '#/components/parameters/nodeId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GetNodeStatusResponse'
              example:
                data:
                  profileUrl: "https://node.site/optional-subdirectory/node-profile.json"
                  nodeId: "59776ca5caf24db9669d847bba3a13bd7052da0a8cccd548a335d8c88d186ce3"
                  lastChecked: 1601979232403
                  status: "posted"
        # TODO: Add non-generic error responses (e.g., `NodeId does not exist`, etc.)
        400:
          $ref: '#/components/responses/BadRequest'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500: 
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - Node Endpoints
      summary: Delete a node from the index
      description: |
        A node can delete its profile from the index at any time simply by removing the profile from its `profileUrl` on its website and then sending this DELETE request to the index.
        
        The index will first confirm the profile is no longer available at the `profileUrl` (node's website should return a `404 - Not Found` error) and then remove the profile from its records. 
      parameters:
        - $ref: '#/components/parameters/nodeId'
      responses:
        200:
          description: OK
        # TODO: Add non-generic error responses (e.g., `NodeId does not exist`, `Profile not yet removed from node`, etc.)
        400:
          $ref: '#/components/responses/BadRequest'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500: 
          $ref: '#/components/responses/ServerError'
 
components:
  schemas:
    PostNodeRequest:
      type: object
      required:
        - profileUrl
        - linkedSchemas
      properties:
        profileUrl:
          type: string
        linkedSchemas:
          type: array
          items:
            type: string
    PostNodeResponse:
      type: object
      properties:
        nodeId:
          type: string
        lastChecked:
          type: number
    GetNodesResponse:
      type: array
      items:
        type: object
        properties:
          profileUrl:
            type: string
          lastChecked:
            type: number
          geolocation:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
          mapAddress:
            type: object
            properties:
              locality:
                type: string
              region:
                type: string
              country:
                type: string
    GetNodeStatusResponse:
      type: object
      properties:
          profileUrl:
            type: string
          nodeId:
            type: string
          lastChecked:
            type: number
          status:
            type: string
            enum:
              - received
              - validated
              - posted
    Error:
      type: object
      title: Error
      properties:
        message:
          type: string
  parameters:
    nodeId:
      name: nodeId
      in: path
      description: The ID of the node
      required: true
      schema:
        type: string
    schemaName:
      name: schema
      in: query
      description: The name of the schema
      required: false
      schema:
        type: string
    lastChecked:
      name: validated
      in: query
      description: Unix timestamp when node was last validated by index
      schema:
        type: string
    latitude:
      name: latitude
      in: query
      description: geolocation latitude coordinate
      schema:
        type: string
    longitude:
      name: longitude
      in: query
      description: geolocation longitude coordinate
      schema:
        type: string
    radius:
      name: radius
      in: query
      description: distance in kilometers from geolocation coordinates
      schema:
        type: string
    locality:
      name: locality
      in: query
      description: town, city, village, etc.
      schema:
        type: string
    region:
      name: region
      in: query
      description: state, province, county, etc.
      schema:
        type: string
    country:
      name: country
      in: query
      description: country, city-state, etc.
      schema:
        type: string
  responses:
    BadRequest:
      description: The request is missing a required parameter.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - message: <named> parameter is missing.
    Unauthorized:
      description: There was an issue with the authentication data for the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - message: Could not authenticate you.
    Forbidden:
      description: User does not have permission to access the resource.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - message: Permission denied.
    TooManyRequests:
      description: The request limit for this resource has been reached for the current rate limit window.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - message: Rate limit exceeded.
    ServerError:
      description: An unknown internal error occurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - message: Internal server error triggered.
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT